services:
  mysql-financeiro:
    image: mysql:8.2.0
    container_name: mysql-financeiro    
    networks:
      - financeiro_network
    environment:
      - MYSQL_DATABASE=financeiro
      - MYSQL_USER=financeiro
      - MYSQL_PASSWORD=Financeiro123456789@
      - MYSQL_ROOT_PASSWORD=Mysql987654321@           
    ports:
      - "3306:3306"
    volumes:
      - /home/reysonbarros/Documents/mysql/financeiro/data:/var/lib/mysql
      - /home/reysonbarros/Documents/mysql/financeiro/config/my.cnf:/etc/my.cnf
  
  financeiro-backend:
    image: reysonbarros/financeiro-api:3.0.6
    container_name: financeiro-api    
    build: .
    networks:
      - financeiro_network
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - MYSQL_ROOT_PASSWORD=Mysql987654321@
      - MYSQL_DATABASE=financeiro
      - MYSQL_USER=financeiro
      - MYSQL_PASSWORD=Financeiro123456789@
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-financeiro:3306/financeiro?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - AWS_S3_BUCKET=s3-financeiro-arquivos
      - AWS_S3_REGION=us-east-2
      - AWS_S3_ENDPOINT=https://s3.us-east-2.amazonaws.com
      - AWS_S3_PREFIX=lancamento-anexo
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    depends_on:
      - mysql-financeiro
    restart: on-failure

networks:
  financeiro_network:
    driver: bridge
