apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  namespace: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
      - name: locust
        image: locustio/locust
        ports:
        - containerPort: 8089
        command: ["locust"]
        args: ["-f", "/mnt/locust/locustfile.py", "--host", "http://financeiro-api.financeiro.svc.cluster.local:9090"]
        volumeMounts:
        - name: locust-script
          mountPath: /mnt/locust
      volumes:
      - name: locust-script
        configMap:
          name: locust-script
