server:
  port: ${SERVER_PORT:9191}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org:
      springframework:
        security: ${LOG_LEVEL_SECURITY:INFO}
    com:
      financeiro:
        api: ${LOG_LEVEL_APP:INFO}

spring:
  jpa:
    database: MYSQL
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  datasource:
    username: ${MYSQL_USER:financeiro}
    password: ${MYSQL_PASSWORD:Financeiro123456789@}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/financeiro?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
  jackson:
    deserialization:
      fail-on-unknown-properties: 'true'
    date-format: yyyy-MM-dd
  threads:
    virtual:
      enabled: ${SPRING_THREADS_VIRTUAL_ENABLED:true}

financeiro:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    issuer: ${JWT_ISSUER}
    timeZone: ${JWT_TIME_ZONE:GMT-3}
    expirationSeconds: ${JWT_EXPIRATION_SECONDS:300} # default 5 minutes